### ISSUE TITLE
IETF RFC 8949 - Concise Binary Object Representation (CBOR), C. Bormann et al., December 2020 

### ISSUE THREAD

**Issue by IshaiO** [eu-digital-identity-wallet/eudi-doc-standards-and-technical-specifications#82]
### Formal name
RFC 8949 - Concise Binary Object Representation (CBOR), C. Bormann et al., December 2020 

### Overview
The Concise Binary Object Representation (CBOR) is a data format whose design goals include the possibility of extremely small code size, fairly small message size, and extensibility without the need for version negotiation. These design goals make it different from earlier binary serializations such as ASN.1 and MessagePack.

See also the PID Rulebook - https://github.com/eu-digital-identity-wallet/eudi-doc-architecture-and-reference-framework/blob/main/docs/annexes/annex-3/annex-3.01-pid-rulebook.md#42-encoding-of-pid-attributes-and-metadata 

### Work Plan
IETF: See https://datatracker.ietf.org/doc/rfc8949/
The EC will pass this technical specification through the MSP process.

### Alerts
+ RFC 8949 received minor changes (with no impacts) through RFC Editor sync (added Errata tag) Errata ID: 8255 (on 2025-01-21)

### References
- https://www.ietf.org/rfc/rfc8949.pdf

**Comment by pinamiranda** [comment]
RFC 8949  -  Received changes (2025-01-21) through RFC Editor sync (added Errata tag) Errata ID: 8255 -> minor change, no impact
